services:
  postgres_db:
    image: postgres:17-alpine
    container_name: local_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_migrations:
    image: ghcr.io/amacneil/dbmate:2
    volumes:
      - ./db/migrations:/db/migrations
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?sslmode=disable
    command: ["up"]
    depends_on:
      postgres_db:
        condition: service_healthy

  web_app:
    build: .
    container_name: go_htmx_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DB_HOST=postgres_db
      - DB_CONTAINER_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
