// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

type Design struct {
	ID          int32
	FormName    string
	LabelName   string
	DataType    string
	IsMandatory bool
	Sequence    int32
}

type SchemaMigration struct {
	Version string
}
