// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

type Design struct {
	ID               int32
	FormName         string
	ControlLevelName string
	ControlType      string
	IsMandatory      bool
	Sequence         int32
}
