// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package query

import (
	"context"
)

const newDesign = `-- name: NewDesign :one
INSERT INTO design (
  form_name ,
  control_level_name ,
  control_type ,
  is_mandatory ,
  sequence 
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, form_name, control_level_name, control_type, is_mandatory, sequence
`

type NewDesignParams struct {
	FormName         string
	ControlLevelName string
	ControlType      string
	IsMandatory      bool
	Sequence         int32
}

func (q *Queries) NewDesign(ctx context.Context, arg NewDesignParams) (Design, error) {
	row := q.db.QueryRow(ctx, newDesign,
		arg.FormName,
		arg.ControlLevelName,
		arg.ControlType,
		arg.IsMandatory,
		arg.Sequence,
	)
	var i Design
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.ControlLevelName,
		&i.ControlType,
		&i.IsMandatory,
		&i.Sequence,
	)
	return i, err
}
