// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllEnterableForms = `-- name: GetAllEnterableForms :many
SELECT f.id, f.form_name, f.enterable
FROM forms f
WHERE f.enterable = true
`

func (q *Queries) GetAllEnterableForms(ctx context.Context) ([]Form, error) {
	rows, err := q.db.Query(ctx, getAllEnterableForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(&i.ID, &i.FormName, &i.Enterable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFormNames = `-- name: GetAllFormNames :many
SELECT f.id, f.form_name, f.enterable
FROM forms f
ORDER BY form_name
`

func (q *Queries) GetAllFormNames(ctx context.Context) ([]Form, error) {
	rows, err := q.db.Query(ctx, getAllFormNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(&i.ID, &i.FormName, &i.Enterable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataRowCountFromFormName = `-- name: GetDataRowCountFromFormName :one
SELECT COUNT(*)
FROM data d
JOIN forms f ON d.form_id = f.id
WHERE f.form_name = $1
`

func (q *Queries) GetDataRowCountFromFormName(ctx context.Context, formName string) (int64, error) {
	row := q.db.QueryRow(ctx, getDataRowCountFromFormName, formName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDesignByFormID = `-- name: GetDesignByFormID :many
SELECT 
  d.id, 
  f.form_name, 
  d.form_id,
  d.label_name, 
  d.data_type, 
  d.is_mandatory, 
  d.sequence,
  d.dropdown_id
FROM design d
JOIN forms f ON d.form_id = f.id
WHERE f.id = $1
ORDER BY d.sequence
`

type GetDesignByFormIDRow struct {
	ID          int32
	FormName    string
	FormID      int32
	LabelName   string
	DataType    DataTypes
	IsMandatory bool
	Sequence    int32
	DropdownID  pgtype.Int4
}

func (q *Queries) GetDesignByFormID(ctx context.Context, id int32) ([]GetDesignByFormIDRow, error) {
	rows, err := q.db.Query(ctx, getDesignByFormID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDesignByFormIDRow
	for rows.Next() {
		var i GetDesignByFormIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FormName,
			&i.FormID,
			&i.LabelName,
			&i.DataType,
			&i.IsMandatory,
			&i.Sequence,
			&i.DropdownID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDesignByFormName = `-- name: GetDesignByFormName :many
SELECT 
  d.id, 
  f.form_name, 
  d.form_id,
  d.label_name, 
  d.data_type, 
  d.is_mandatory, 
  d.sequence,
  d.dropdown_id
FROM design d
JOIN forms f ON d.form_id = f.id
WHERE f.form_name = $1
ORDER BY d.sequence
`

type GetDesignByFormNameRow struct {
	ID          int32
	FormName    string
	FormID      int32
	LabelName   string
	DataType    DataTypes
	IsMandatory bool
	Sequence    int32
	DropdownID  pgtype.Int4
}

func (q *Queries) GetDesignByFormName(ctx context.Context, formName string) ([]GetDesignByFormNameRow, error) {
	rows, err := q.db.Query(ctx, getDesignByFormName, formName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDesignByFormNameRow
	for rows.Next() {
		var i GetDesignByFormNameRow
		if err := rows.Scan(
			&i.ID,
			&i.FormName,
			&i.FormID,
			&i.LabelName,
			&i.DataType,
			&i.IsMandatory,
			&i.Sequence,
			&i.DropdownID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFormNameFromID = `-- name: GetFormNameFromID :one
SELECT form_name
FROM forms 
WHERE id = $1
`

func (q *Queries) GetFormNameFromID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getFormNameFromID, id)
	var form_name string
	err := row.Scan(&form_name)
	return form_name, err
}

const getNextFormEntryId = `-- name: GetNextFormEntryId :one
SELECT COALESCE(MAX(form_entry_id), 0) + 1 FROM data WHERE form_id = $1
`

func (q *Queries) GetNextFormEntryId(ctx context.Context, formID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextFormEntryId, formID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOptionsDropDownBox = `-- name: GetOptionsDropDownBox :many
SELECT unnest(dd.options)::text AS option_value
FROM design d
JOIN dropdown dd ON d.dropdown_id = dd.id
WHERE d.label_name = $1 
  AND d.form_id = $2
`

type GetOptionsDropDownBoxParams struct {
	LabelName string
	FormID    int32
}

func (q *Queries) GetOptionsDropDownBox(ctx context.Context, arg GetOptionsDropDownBoxParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getOptionsDropDownBox, arg.LabelName, arg.FormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var option_value string
		if err := rows.Scan(&option_value); err != nil {
			return nil, err
		}
		items = append(items, option_value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRowCountFromFormName = `-- name: GetRowCountFromFormName :one
SELECT COUNT(*)
FROM design d
JOIN forms f ON d.form_id = f.id
WHERE f.form_name = $1
`

func (q *Queries) GetRowCountFromFormName(ctx context.Context, formName string) (int64, error) {
	row := q.db.QueryRow(ctx, getRowCountFromFormName, formName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllDesigns = `-- name: ListAllDesigns :many
SELECT 
  d.id, 
  f.form_name, 
  d.form_id,
  d.label_name, 
  d.data_type, 
  d.is_mandatory, 
  d.sequence,
  d.dropdown_id
FROM design d
JOIN forms f ON d.form_id = f.id
ORDER BY f.form_name, d.sequence
`

type ListAllDesignsRow struct {
	ID          int32
	FormName    string
	FormID      int32
	LabelName   string
	DataType    DataTypes
	IsMandatory bool
	Sequence    int32
	DropdownID  pgtype.Int4
}

func (q *Queries) ListAllDesigns(ctx context.Context) ([]ListAllDesignsRow, error) {
	rows, err := q.db.Query(ctx, listAllDesigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDesignsRow
	for rows.Next() {
		var i ListAllDesignsRow
		if err := rows.Scan(
			&i.ID,
			&i.FormName,
			&i.FormID,
			&i.LabelName,
			&i.DataType,
			&i.IsMandatory,
			&i.Sequence,
			&i.DropdownID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newDataEntry = `-- name: NewDataEntry :one
INSERT INTO data (
  data, 
  data_type,
  form_id,
  form_entry_id
) VALUES (
  $1,
  $2,
  $3,
  $4 
)
RETURNING id, data, data_type, dropdown_id, form_id, form_entry_id
`

type NewDataEntryParams struct {
	Data        string
	DataType    DataTypes
	FormID      int32
	FormEntryID int32
}

func (q *Queries) NewDataEntry(ctx context.Context, arg NewDataEntryParams) (Datum, error) {
	row := q.db.QueryRow(ctx, newDataEntry,
		arg.Data,
		arg.DataType,
		arg.FormID,
		arg.FormEntryID,
	)
	var i Datum
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.DataType,
		&i.DropdownID,
		&i.FormID,
		&i.FormEntryID,
	)
	return i, err
}

const newDesign = `-- name: NewDesign :one
WITH target_form AS (
  INSERT INTO forms (form_name)
  VALUES ($1)
  ON CONFLICT (form_name) DO UPDATE 
    SET form_name = EXCLUDED.form_name 
  RETURNING id
),
inserted AS (
  INSERT INTO design (
    form_id, 
    label_name,
    data_type,
    is_mandatory,
    sequence, 
    dropdown_id
  ) VALUES (
    (SELECT id FROM target_form),
    $2,
    $3::data_types, 
    $4,
    $5,
    $6
  )
  RETURNING id, label_name, data_type, is_mandatory, sequence, dropdown_id, form_id
)
SELECT 
  i.id, 
  $1::VARCHAR AS form_name,
  i.label_name, 
  i.data_type, 
  i.is_mandatory, 
  i.sequence,
  i.dropdown_id
FROM inserted i
`

type NewDesignParams struct {
	Column1     string
	LabelName   string
	Column3     DataTypes
	IsMandatory bool
	Sequence    int32
	DropdownID  pgtype.Int4
}

type NewDesignRow struct {
	ID          int32
	FormName    string
	LabelName   string
	DataType    DataTypes
	IsMandatory bool
	Sequence    int32
	DropdownID  pgtype.Int4
}

func (q *Queries) NewDesign(ctx context.Context, arg NewDesignParams) (NewDesignRow, error) {
	row := q.db.QueryRow(ctx, newDesign,
		arg.Column1,
		arg.LabelName,
		arg.Column3,
		arg.IsMandatory,
		arg.Sequence,
		arg.DropdownID,
	)
	var i NewDesignRow
	err := row.Scan(
		&i.ID,
		&i.FormName,
		&i.LabelName,
		&i.DataType,
		&i.IsMandatory,
		&i.Sequence,
		&i.DropdownID,
	)
	return i, err
}

const newDropDown = `-- name: NewDropDown :one
INSERT INTO dropdown (
  options
) VALUES (
  $1
) 
RETURNING id, options
`

func (q *Queries) NewDropDown(ctx context.Context, options []string) (Dropdown, error) {
	row := q.db.QueryRow(ctx, newDropDown, options)
	var i Dropdown
	err := row.Scan(&i.ID, &i.Options)
	return i, err
}

const setFormEnterable = `-- name: SetFormEnterable :exec
UPDATE forms 
SET enterable = true
WHERE form_name = $1
`

func (q *Queries) SetFormEnterable(ctx context.Context, formName string) error {
	_, err := q.db.Exec(ctx, setFormEnterable, formName)
	return err
}
